function plot_spec(f, S, info_Spec)

    plot(f, S, 'LineWidth', 1.5, 'Color', 'black')

    tit = title('S(f)');
    xl = xlabel('f (Hz)');
    yl = ylabel('S(f) (m^2/Hz)');

    grid on

    xl.FontSize  = 12;
    yl.FontSize  = 12;
    tit.FontSize = 14;

    %% Texto del cuadro

    texto = sprintf([ ...
        'DoF: %g\n' ...
        'window: %s\n' ...
        'M: %g\n' ...
        'N: %g\n' ...
        'N0: %g\n' ...
        'K: %g\n' ...
        'Nfft: %g\n' ...
        'var: %.2g m^2\n' ...
        'm0: %.2g m^2\n' ...
        'err: %.2g %%\n' ...
        'resolution: %.3g Hz\n' ...
        'resolution: %.3g s'], ...
        info_Spec.DoF, ...
        info_Spec.window, ...
        info_Spec.M, ...
        info_Spec.N, ...
        info_Spec.N0, ...
        info_Spec.K, ...
        info_Spec.Nfft, ...
        info_Spec.varianza, ...
        info_Spec.m0, ...
        info_Spec.error_relativo, ...
        info_Spec.resolution_Hz, ...
        info_Spec.resolution_s);

    cuadro_texto = text(0.6, 0.9, texto, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'EdgeColor', 'black', ...
        'BackgroundColor', 'white', ...
        'Margin', 8, ...
        'FontSize', 8);

end